//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShopingStore.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_MemberRole
    {
        public int MemberRoleId { get; set; }
        public Nullable<int> MemberId { get; set; }
        public Nullable<int> RoleId { get; set; }
    
        public virtual Tbl_Members Tbl_Members { get; set; }
        public virtual Tbl_role Tbl_role { get; set; }
    }
}
